# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-26 11:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('moneypool_management', '0001_initial'),
        ('payment', '0027_auto_20180726_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='cashout',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loan', to='payment.MoneypoolCashout'),
        ),
        migrations.AddField(
            model_name='installment',
            name='cashin',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='installment', to='payment.MoneypoolCashin'),
        ),
        migrations.AddField(
            model_name='installment',
            name='loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='moneypool_management.Loan'),
        ),
        migrations.AlterUniqueTogether(
            name='poolship',
            unique_together=set([('member', 'moneypool', 'id')]),
        ),
    ]
