# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-02-03 13:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moneypool_management', '0021_auto_20190114_1546'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoneypoolCommission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('removed', models.DateTimeField(blank=True, default=None, editable=False, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('is_manually_set', models.BooleanField(default=False, verbose_name='Is Manually Set')),
                ('portion_commission_coef', models.FloatField(default=1.0, verbose_name='Portion Commission Coef.')),
                ('installment_commission_coef', models.FloatField(default=1.0, verbose_name='Installment Commission Coef.')),
                ('custom_cashin_commission_coef', models.FloatField(default=1.0, verbose_name='Custom Commission Coef.')),
                ('number_of_trial_intervals', models.IntegerField(default=1, verbose_name='No. of Trial Intervals')),
                ('number_of_trial_installments', models.IntegerField(default=1, verbose_name='No. of Trial Installments')),
                ('number_of_trial_custom_cashins', models.IntegerField(default=1, verbose_name='No. of Trial Custom Cashins')),
                ('moneypool', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='moneypool_management.Moneypool')),
            ],
            options={
                'verbose_name': 'Moneypool Commission',
                'verbose_name_plural': 'Moneypool Commissions',
            },
        ),
    ]
