# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-05-13 13:57
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models

from utils.constants import choice


class Migration(migrations.Migration):

    # feeding obj_id & obj_type before removing cycle & moneypool
    # migrations.RunPython(migration_utils.feed_obj_id_and_type, reverse_code=migrations.RunPython.noop),
    def feed_ctx_id_and_type(apps, schema_editor):
        Transaction = apps.get_model('payment', 'Transaction')
        for tr in Transaction.objects.all():
            if tr.cycle:
                tr.ctx_type = choice.TRANSACTION_CTX_TYPE_CYCLE
                tr.ctx_id = tr.cycle.id
            elif tr.moneypool:
                tr.ctx_type = choice.TRANSACTION_CTX_TYPE_MONEYPOOL
                tr.ctx_id = tr.moneypool.id

            if tr.source == choice.TRANSACTION_SRC_WALLET:
                tr.source = choice.TRANSACTION_SRC_HAMYAN_WALLET
            elif tr.source in (choice.TRANSACTION_SRC_CASHBOX, choice.TRANSACTION_SRC_MONEYPOOL):
                tr.source = choice.TRANSACTION_SRC_HAMYAN_BOX_BALANCE

            if tr.destination == choice.TRANSACTION_DST_WALLET:
                tr.destination = choice.TRANSACTION_DST_HAMYAN_WALLET
            elif tr.destination in (choice.TRANSACTION_DST_CASHBOX, choice.TRANSACTION_DST_MONEYPOOL):
                tr.destination = choice.TRANSACTION_DST_HAMYAN_BOX_BALANCE
            elif tr.destination == choice.TRANSACTION_DST_CASH:
                tr.destination = choice.TRANSACTION_DST_MEMBER_BANKACCOUNT

            tr.save()

    dependencies = [
        ('payment', '0034_auto_20181225_1047'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-id'], 'verbose_name': 'Transaction', 'verbose_name_plural': 'Transactions'},
        ),
        migrations.AddField(
            model_name='transaction',
            name='ctx_id',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Ctx ID'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='ctx_type',
            field=models.CharField(choices=[('ccl', 'Cycle'),
                                            ('mnp', 'Moneypool'),
                                            ('mbr', 'Member')], default='ccl', max_length=5, verbose_name='Ctx Type'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='source',
            field=models.CharField(choices=[('wlt', 'wallet'),
                                            ('csb', 'cashbox'),
                                            ('mnp', 'moneypool'),
                                            ('bkc', 'bankaccount'),
                                            ('gtw', 'gateway'),
                                            ('hpl', 'hamyan pool'),
                                            ('hwt', 'hamyan wallet'),
                                            ('hbb', 'hamyan box balance'),
                                            ('bba', 'box bankaccount'),
                                            ('mba', 'member bankaccount'),
                                            ], default='gtw', max_length=5, verbose_name='Source'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='destination',
            field=models.CharField(choices=[('wlt', 'wallet'),
                                            ('csb', 'cashbox'),
                                            ('mnp', 'moneypool'),
                                            ('bkc', 'bankaccount'),
                                            ('csh', 'cash'),
                                            ('hpl', 'hamyan pool'),
                                            ('hwt', 'hamyan wallet'),
                                            ('hbb', 'hamyan box balance'),
                                            ('bba', 'box bankaccount'),
                                            ('mba', 'member bankaccount'),
                                            ], default='hbb', max_length=5, verbose_name='Destination'),
        ),

        migrations.RunPython(feed_ctx_id_and_type, reverse_code=migrations.RunPython.noop),

        migrations.RenameField(
            model_name='transaction',
            old_name='successful_time',
            new_name='state_time'
        ),
        migrations.AlterField(
            model_name='transaction',
            name='source',
            field=models.CharField(choices=[('gtw', 'gateway'),
                                            ('hpl', 'hamyan pool'),
                                            ('hwt', 'hamyan wallet'),
                                            ('hbb', 'hamyan box balance'),
                                            ('bba', 'box bankaccount'),
                                            ('mba', 'member bankaccount'),
                                            ], default='gtw', max_length=5, verbose_name='Source'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='destination',
            field=models.CharField(choices=[('hpl', 'hamyan pool'),
                                            ('hwt', 'hamyan wallet'),
                                            ('hbb', 'hamyan box balance'),
                                            ('bba', 'box bankaccount'),
                                            ('mba', 'member bankaccount'),
                                            ], default='hbb', max_length=5, verbose_name='Destination'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='state_time',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='State Time'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='rrn',
            field=models.CharField(blank=True, default='', max_length=400, verbose_name='RRN'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='wrd_transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_transaction', to='payment.Transaction'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.IntegerField(default=0, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='commission',
            field=models.IntegerField(default=0, verbose_name='Commission'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='is_group_pay',
            field=models.BooleanField(default=False, verbose_name='Group Pay'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='manually_created',
            field=models.BooleanField(default=False, verbose_name='Manually Created'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='mother_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daughter_transactions', to='payment.Transaction'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='state',
            field=models.CharField(choices=[('init', 'Initialized'), ('tknd', 'Tokened'), ('inpg', 'In-Progress'), ('tbnk', 'To-Bank'), ('scss', 'Successful'), ('unsc', 'Unsuccessful')], default='init', max_length=10, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='token',
            field=models.CharField(blank=True, default='', max_length=400, verbose_name='Token'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_code',
            field=models.CharField(default='', max_length=10, verbose_name='Transaction Code'),
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='cycle',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='moneypool',
        ),
    ]
