# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-08-19 13:45
from __future__ import unicode_literals

from django.db import migrations, models
from utils.constants import choice

class Migration(migrations.Migration):

    def feed_member_plan(apps, schema_editor):
        Member = apps.get_model('account_management', 'Member')
        for member in Member.objects.all():
            member.plan = choice.MEMBER_PLAN_HAMYAN
            member.save()
    dependencies = [
        ('account_management', '0034_auto_20190810_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='plan',
            field=models.CharField(choices=[('mph', 'Plan Hamyan'), ('mpf', 'Plan Freemium')], default='mpf', max_length=6),
        ),
        migrations.RunPython(feed_member_plan, reverse_code=migrations.RunPython.noop)
    ]
