# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2020-05-14 07:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0006_auto_20200429_1244'),
        ('setting', '0007_auto_20200430_2005'),
    ]

    operations = [
    ]
